global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.mailtrap.io:2525'
  smtp_from: 'test_user'
  smtp_auth_username: 'test_user'
  smtp_auth_password: 'test_pass'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-admin'

receivers:
  - name: 'email-admin'
    email_configs:
      - to: 'admin@copilot-analytics.com'
        send_resolved: true
