global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-admin'

receivers:
  - name: 'email-admin'
    email_configs:
      - to: 'admin@copilot-analytics.com'
        from: 'alerts@copilot-analytics.com'
        smarthost: 'smtp:25'
        require_tls: false
