global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dashboard'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['dashboard:3000']

  - job_name: 'batch-processor'
    metrics_path: /metrics
    static_configs:
      - targets: ['batch-processor:8080']
