{
 "title": "System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m]) * 100",
     "legendFormat": "{{job}} CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}} Memory Usage" }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{job}} Event Loop Lag" }
   ]
  }
 ]
}